set(_CATKIN_CURRENT_PACKAGE "basestation_ersow")
set(basestation_ersow_VERSION "0.1.0")
set(basestation_ersow_MAINTAINER "agus <agus@gmail.com>")
set(basestation_ersow_PACKAGE_FORMAT "1")
set(basestation_ersow_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev" "roslaunch" "roscpp" "std_msgs" "geometry_msgs" "message_generation")
set(basestation_ersow_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev" "roslaunch" "roscpp" "std_msgs" "geometry_msgs" "message_runtime")
set(basestation_ersow_BUILDTOOL_DEPENDS "catkin")
set(basestation_ersow_BUILDTOOL_EXPORT_DEPENDS )
set(basestation_ersow_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev" "roslaunch" "roscpp" "std_msgs" "geometry_msgs" "message_runtime")
set(basestation_ersow_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev" "roslaunch" "std_msgs" "geometry_msgs" "message_runtime")
set(basestation_ersow_TEST_DEPENDS )
set(basestation_ersow_DOC_DEPENDS )
set(basestation_ersow_URL_WEBSITE "")
set(basestation_ersow_URL_BUGTRACKER "")
set(basestation_ersow_URL_REPOSITORY "")
set(basestation_ersow_DEPRECATED "")